/**:
  ros__parameters:
    world_frame: "world"
    agent_frame: "base"
    agent_prefix: "agent"

    kp: 1.0
    timer_period: 0.1
    dt: 0.1

    x_wall: [1.0, 0.0, -1.0]
    y_wall: [0.0, 1.0, 0.0]
    cbf_keep_inside: False
    delta_decrease: 0.5
    delta_increase: 0.05
    sensing_radius: 0.3
    d: 0.01