/**:
  ros__parameters:
    world_frame: "world"
    agent_frame: "base"
    agent_prefix: "agent"

    kp: 1.0
    timer_period: 0.1
    dt: 0.1

    cbf_x_limit: [-0.5, 1.5]
    cbf_y_limit: [-0.3, 0.8]
    cbf_theta: 0.1
    cbf_keep_inside: False
    delta_decrease: 0.5
    delta_increase: 0.05
    sensing_radius: 0.3
